outdir: "outdir"
outpath: "outfile.root"
inpath: "/RGA_DT_DIR/skim_*.root"
tree: "t"
nthreads: 8
cuts: "mass_ppim<1.24 && Q2>1 && W>2 && y<0.8 && xF_ppim>0.0 && z_ppim<1.0 && detector_p==6 && detector_pim==6 && vz_e>-10 && vz_e<2.5"
sgcuts: "mass_ppim>1.1104 && mass_ppim<1.12959" #NOTE: CHOSE SO THAT THESE COINCIDE WITH THE RIGHT BINS IN YOUR INVARIANT MASS HISTOGRAM.
bgcuts: "(mass_ppim>1.08 && mass_ppim<1.11) || (mass_ppim>1.15 && mass_ppim<1.18)"
method: "HB"
fitvar: "costheta1"
binvars:
  nu:
    bins: [0.0, 10.0]
    poly4bins: [1]
  Q2:
    bins: [1.0000, 1.2248, 1.5243, 1.9571, 2.7212, 11.0]
    poly4bins: [5]
  W:
    bins: [2.0000, 2.2569, 2.4926, 2.7605, 3.1145, 5.0]
    poly4bins: [5]
  y:
    bins: [0.0000, 0.3071, 0.3736, 0.4517, 0.5635, 0.8]
    poly4bins: [4,5]
  x:
    bins: [0.0000, 0.1515, 0.2033, 0.2564, 0.3339, 1.0]
    poly4bins: [1]
  xF_ppim:
    bins: [0.0000, 0.0504, 0.1082, 0.1784, 0.2775, 1.0]
    poly4bins: [5]
  z_ppim:
    bins: [0.0000, 0.5928, 0.6856, 0.7698, 0.8597, 1.0]
    poly4bins: [1]
bgfraction: 1.0
use_bgfraction: false
inject_asym: false
sgasym: 0.00
bgasym: 0.00
beam_polarization: 0.8922 # Average Polarization for Fall 2018 Outbending data runs >= 5331
mass_name: "mass_ppim"
n_mass_bins: 100
mass_nbins_conv: 1000
mass_min: 1.08
mass_max: 1.24
mass_draw_opt: ""
graph_title: ""
marker_color: 4
marker_style: 20
logpath: "out.txt"
workspace_name: "w"
workspace_title: "workspace"
dataset_name: "dataset"
dataset_title: "dataset"
sig_pdf_name1: "cb"
sig_pdf_name2: "gauss"
sgYield_name: "sgYield"
bgYield_name: "bgYield"
sg_region_min: 1.11040
sg_region_max: 1.12959
